name: Diamond Glorius CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DG_GITHUB_TOKEN }}
      - name: Build the Docker image
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          API_URL: ${{ secrets.API_URL }}
          CAPTCHA_KEY: ${{secrets.CAPTCHA_KEY}}
        run: |
          docker build --build-arg API_TOKEN=${{ secrets.API_TOKEN }} --build-arg API_URL=${{ secrets.API_URL }} --build-arg CAPTCHA_KEY=${{ secrets.CAPTCHA_KEY }} . --tag ghcr.io/ekaramyan/DiamondGlorius:latest
          docker push ghcr.io/ekaramyan/DiamondGlorius:latest
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            bash ~/home/diamond/bootstrap.sh nextjs
